circle_position1 = None
circle_position2=None
circle_position3=None
circle_position4=None
circle_position5=None
circle_position6=None
circle_position7=None
circle_position8=None
circle_position9=None
circle_position11 =None
circle_position22=None
circle_position33=None
circle_position44=None
circle_position55=None
circle_position66=None
circle_position77=None
circle_position88=None
circle_position99=None