cross_position1 = None
cross_position2=None
cross_position3=None
cross_position4=None
cross_position5=None
cross_position6=None
cross_position7=None
cross_position8=None
cross_position9=None
cross_position11=None
cross_position22=None
cross_position33=None
cross_position44=None
cross_position55=None
cross_position66=None
cross_position77=None
cross_position88=None
cross_position99=None